### ISSUE TITLE
White Screen on the admin App - Users screen

### ISSUE THREAD

**Issue by ronyrun** [hoodiehq/hoodie-plugin-users#42]
I did create some users with APis and with the Test APP. And on my http://127.0.0.1:6005/#plugin/users admin app I have a White Screen when I' supposed to be able to manage the users.

errors in the console : 

GET http://127.0.0.1:6005/_api/plugins/_changes?include_docs=true&since=0 401 (Unauthorized)
vendor.js:5 
Uncaught ReferenceError: Backbone is not define

Here is the npm ls --json
http://pastebin.com/pj3t1VFX

**Comment by mattvot** [comment]
+1 Exactly the same issue

**Comment by mattvot** [comment]
This issue comes from the remove of content in plugins.js from 2a8632b179e77af6806

**Comment by mattvot** [comment]
Is this something @gr2m could take a look at?

Unless this is part of an architectural change and placing the content back in the file will fix it, I'm happy to create a pull request.

**Comment by gr2m** [comment]
looking into it now, sorry I'm not available a lot to help better at the moment

**Comment by gr2m** [comment]
should be solved via 
https://github.com/hoodiehq/hoodie-plugin-users/commit/a488d987750e52d1c897b6d97daf42583a86cf9b

The `GET http://127.0.0.1:6005/_api/plugins/_changes?include_docs=true&since=0 401 (Unauthorized)` problem should be fixed via https://github.com/hoodiehq/hoodie.admin.js/commit/5cac164b611df9e64543ed2206316fb9d6568723

When you create a new hoodie app, it should already be solved. On existing apps, update `"hoodie-plugin-users": "^2.2.1"` in your package.json, `rm -rf node_modules` and `npm install` should do the trick

**Comment by gr2m** [comment]
please reopen if error persists <3

**Comment by mattvot** [comment]
Thanks @gr2m

**Comment by nintra** [comment]
Still doesnt work for me. admin-dashboard-uikit.css and admin-dashboard-uikit.js just dont exist.

![dashboard-error](https://cloud.githubusercontent.com/assets/1950290/6771894/fe0ba286-d0ed-11e4-9a59-b1be71852619.png)

**Comment by gr2m** [comment]
@nintra when you create a fresh new app with Hoodie, do you see that, too? Run `npm cache clean` first to be sure. 

If it works in the fresh Hoodie app, can you run `npm ls` in both and compare the versions of the dependencies?

**Comment by nintra** [comment]
@gr2m 
It's similiar. Still doesn't work. I called ```npm cache clean```, uninstalled / installed hoodie-cli globally and created a new app with ```hoodie new testapp```. The app was created with older dependencies. But with your suggested plugin-users version.
```
"version": "3.0.6",
"type": "app",
"dependencies": {
    "hoodie-server": "^3.0.0",
    "hoodie-plugin-appconfig": "^2.0.1",
    "hoodie-plugin-email": "^1.0.0",
    "hoodie-plugin-users": "^2.2.1"
},
```

Yesterday i've created a new app but updated all dependencies to latest.
```
"dependencies": {
    "hoodie-server": "latest",
    "hoodie-plugin-appconfig": "latest",
    "hoodie-plugin-email": "latest",
    "hoodie-plugin-users": "latest"
},
```

It looks similar. No dashboard js, no dashboard css loaded. But there is a little difference i think. Before your update the files where ```404 Not Found```. But now if you want to ```GET``` css js it redirects to the testapp ```index.html```
